from time import sleep

from userbot import CMD_HELP, CMD_HANDLER as cmd
from userbot.utils import Xa_cmd


@Xa_cmd(pattern="bii$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("BIIIIIIIIIII⭐")
        sleep(1)
        await e.edit("💜⭐✨🌠")
        sleep(1)
        await e.edit("⭐⭐⭐⭐")
        sleep(1)
        await e.edit("⭐✨🌠💜")
        sleep(1)
        await e.edit("BII🌠✨")
        sleep(1)
        await e.edit("BINTANG💜⭐💜")
        sleep(1)
        await e.edit("🌠⭐💜✨")
        sleep(1)
        await e.edit("BII CANTIK💜")
        sleep(1)
        await e.edit("💜⭐🌠✨")
        await e.edit("💜💜💜💜")
        await e.edit("⭐🌠✨💜")
        await e.edit("BII IMUT")
        sleep(1)
        await e.edit("BIIII LUCU")
        sleep(1)
        await e.edit("BI SUKA REXA SUKA")
        sleep(1)
        await e.edit("✨💜🌠⭐")
        sleep(1)
        await e.edit("BII BAIK")
        sleep(1)
        await e.edit("CUMA MAU BILANG")
        sleep(1)
        await e.edit("BII CANTIK BANGET💜")
        sleep(1)
        await e.edit("TAPI NGESELIN HUU🤣")
        sleep(1)
        await e.edit("BII BII BII ⭐")
        sleep(2)
        await e.edit("BINTANGGG REXA SUKA KATANYA")
        sleep(2)
        await e.edit("UDAH CINTA JUGA KATANYA")
        sleep(1)
        await e.edit("BIIIIIIII⭐⭐⭐")
        sleep(2)
        await e.edit("BII I LOVE YOU💞")


@Xa_cmd(pattern="orgil(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`ANJING ADA ORANG GILA.....`")
    sleep(1)
    await typew.edit("`ORANG GILAAAAAA!!`")
    sleep(1)
    await typew.edit("`🏃                        🤸`")
    await typew.edit("`🏃                       🤸`")
    await typew.edit("`🏃                      👨‍🦽`")
    await typew.edit("`🏃                     ⛹️`")
    await typew.edit("`🏃   `LARII`          🤾`")
    await typew.edit("`🏃                   🤾`")
    await typew.edit("`🏃                  🤾`")
    await typew.edit("`🏃                 🤾`")
    await typew.edit("`🏃                🤾`")
    await typew.edit("`🏃               🤺`")
    await typew.edit("`🏃              🏊`")
    await typew.edit("`🏃             🏊`")
    await typew.edit("`🏃            🏄`")
    await typew.edit("`🏃           🤾`")
    await typew.edit("`🏃PULUPULU   🧚`")
    await typew.edit("`🏃           ⛹️`")
    await typew.edit("`🏃            ⛹️`")
    await typew.edit("`🏃             🤺`")
    await typew.edit("`🏃              🥴`")
    await typew.edit("`🏃               🏃`")
    await typew.edit("`🏃                🏃`")
    await typew.edit("`🏃                 🤸`")
    await typew.edit("`🏃                  🤸`")
    await typew.edit("`🏃                   🤸`")
    await typew.edit("`🏃                    🤸`")
    await typew.edit("`🏃                     ⛹️`")
    await typew.edit("`🏃  Huh-Huh           🏃`")
    await typew.edit("`🏃                   🤑`")
    await typew.edit("`🏃                  🙈`")
    await typew.edit("`🏃                 ⛹️`")
    await typew.edit("`🏃                🏃`")
    await typew.edit("`🏃               🤴`")
    await typew.edit("`🏃              🐖`")
    await typew.edit("`🏃             🐖`")
    await typew.edit("`🏃            🥴`")
    await typew.edit("`🏃           🥴`")
    await typew.edit("`🏃          🤡`")
    await typew.edit("`🏃         🤭`")
    await typew.edit("`CAPE BANGET ANJING!!!`")
    sleep(1)
    await typew.edit("`🏃       🏃`")
    await typew.edit("`🏃      🤾`")
    await typew.edit("`🏃     🏃`")
    await typew.edit("`🏃    🏃`")
    await typew.edit("`Dahlah Pasrah Aja`")
    sleep(1)
    await typew.edit("`🧎🐖`")
    sleep(2)
    await typew.edit("`-TAMAT-`")


@Xa_cmd(pattern="bintang(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`Mau ngasih tau sebentar....`")
    sleep(2)
    await typew.edit("`B`")
    await typew.edit("`Bi`")
    await typew.edit("`Bin`")
    await typew.edit("`Bint`")
    await typew.edit("`Binta`")
    await typew.edit("`Bintang`")
    await typew.edit("`Bintang R`")
    await typew.edit("`Bintang Re`")
    await typew.edit("`Bintang Rex`")
    await typew.edit("`Bintang Rexa`")
    await typew.edit("`Bintang Rexa S`")
    await typew.edit("`Bintang Rexa Sa`")
    await typew.edit("`Bintang Rexa Say`")
    await typew.edit("`Bintang Rexa Saya`")
    await typew.edit("`Bintanh Rexa Sayang`")
    sleep(3)
    await typew.edit("**BII JUGA SAYANG KAN?**")
# Create by myself @ram-ubot


CMD_HELP.update({
    "animasi7": f"`{cmd}gabut` ; `{cmd}orgil`\
    \nUsage: ntahlah gabut doang.\
    \n\n`{cmd}bintang`\
    \nUsage: Mau ngasih tau ke bii."
})

CMD_HELP.update({
    "animasi8": f"`{cmd}cinta`\
    \nUsage: mengirim cintamu ke seseorang.\
    \n\n`{cmd}bii` :\
    \nUsage: Special command for @Aiibiie ."
})
